name: PHP Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpunit
      - name: Run PHPUnit
        run: phpunit --configuration phpunit.xml
